[build]
publish = "public"

[functions]
directory = "netlify/functions"
node_bundler = "esbuild"

[[headers]]
for = "/*"

  [headers.values]
  Cache-Control = "no-store"
  X-Content-Type-Options = "nosniff"
  Referrer-Policy = "no-referrer"
