name: ai_knowledge_flutter_app
description: Flutter native client for the AI Knowledge Base app.
publish_to: "none"
version: 1.0.11+136

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  file_selector: ^1.0.3
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.4+1
  http: ^1.2.2
  image_picker: ^1.1.2
  permission_handler: ^11.3.1
  provider: ^6.1.2
  shared_preferences: ^2.3.2
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
